<br>
<div class="row container-fluid">

    <div class="panel panel-default">
        <div class="panel-heading">Edit Record</div>
        <div class="panel-body">
            <?php
            $form = $this->grid->getEntityForm();
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();
//$form->setAttribute('action', $this->url('application', array('action' => 'edit')))->prepare();
            echo $this->gview->form()->openTag($form);
            ?>


            <?php $multiplo = 2; ?>
            <?php $countRow = 2; ?>
            <?php foreach ($form as $element) : ?>

                <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
                        <?php echo $this->gview->formElement($element); ?>
                        <?php break; ?>
                    <?php case "submit": ?>
                        <?php $element->setAttribute('class', 'btn btn-success'); ?>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-xs-12 ">
                                <div  class="form-group">
                                    <div class="col-lg-3 col-md-3 col-xs-12">
                                        <?php echo $this->gview->formElement($element); ?>
                                        <a class="btn btn-default" href="<?php echo $this->gview->url($this->route, array(), array('query' => $this->routeParams), true); ?>" >Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php break; ?>
                    <?php default: ?>

                        <?php
                        $element->setAttribute('class', 'form-control');
                        //  ->setAttribute('placeholder', $element->getLabel());
                        ?>
                        <div class="row">


                            <div class="col-lg-12 col-md-12 col-xs-12">
                                <div  class="form-group<?php if ($this->gview->formElementErrors($element)) echo " has-error" ?>">

                                    <label class="col-lg-4 col-md-4 control-label"><?php echo $element->getLabel() ?></label>

                                    <div class="col-lg-8 col-md-8">
                                        <?php echo $this->gview->formElement($element); ?>
                                        <?php if ($element->getOption('description')): ?>
                                            <p class="help-block"><?php echo $element->getOption('description') ?></p>
                                        <?php endif; ?>
                                        <?php if ($this->gview->formElementErrors($element)) : ?>
                                            <?php
                                            // Imprimo los errores
                                            echo $this->gview->formElementErrors()
                                                    ->setMessageOpenFormat('<span class="help-block">')
                                                    ->setMessageSeparatorString('</span><span class="help-block">')
                                                    ->setMessageCloseString('</span>')
                                                    ->render($element);
                                            ?>

                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>

                        </div>


                        <?php break; ?>
                <?php endswitch; ?>

            <?php endforeach; ?>

            <?php echo $this->gview->form()->closeTag($form); ?>
        </div>
    </div>
</div>
