<script>


    function loadObjectFormToModal( objectId,modalId, urlAjax, containerResponseId) {
        $('#' + containerResponseId).html("<i class='fa fa-cog fa-spin'></i><span> Cargando...</span>");
        $('#' + modalId).modal('show');
        $.get(urlAjax, {id: objectId})
                .done(function (data) {
                    $('#' + containerResponseId).html(data);


                }); 

    }

    function submitFormByAjax(formId, urlAjax, containerResponseId) {

        var datastring = $('#' + formId).serialize();
        $('#' + containerResponseId).html("<i class='fa fa-cog fa-spin'></i><span> Cargando...</span>");
        $.post(urlAjax, datastring)
                .done(function (data) {
                    $('#' + containerResponseId).html(data);

                });

    }
    
    function deleteObject(objectId,modalId, urlAjax, containerResponseId){
        
    }

</script>