<script>

    function deleteObject(objectId){
        if(confirm("¿Esta seguro que desea eliminar el registro?")){
            var goto = window.location.href;
            goto += "?crudAction=delete&id="+objectId;
            //window.location.assign(goto)
            alert("vanana");
        }
    }
    
    function editObject(objectId){
            var goto = window.location.href;
            goto += "?crudAction=edit&id="+objectId;
            window.location.assign(goto)
    }
    
    function addObject(){
            var goto = window.location.href;
            goto += "?crudAction=add";
            window.location.assign(goto)
    }

</script>