<style>
    .table .tauto td , .table .tauto th, .table .tauto{
        width: auto !important;
    }
    .table .tauto input[type='text'], .table .tauto select{
        width: 90% !important;
    }

</style>

<br>
<div class="row">
    <div class="col-xs-12">
        <?php if ($this->grid->getCsvCommaOn()): ?>
            <a class="btn btn-info" href="<?php echo $this->gview->url($this->route, array(), array('query' => array('cdiExportCommaCsv' => "yes") + $this->routeParams), true); ?>">Exportar CSV (,)</a> 

        <?php endif; ?>
        <?php if ($this->grid->getCsvSemicolonOn()): ?>
            <a class="btn btn-info" href="<?php echo $this->gview->url($this->route, array(), array('query' => array('cdiExportSemiColonCsv' => "yes") + $this->routeParams), true); ?>">Exportar CSV (;)</a> 

        <?php endif; ?>

    </div>
</div>
<br>
<?php
$form = $this->grid->getFormFilters();
$form->prepare();

$submit = $form->get("submit");
$submit->setAttribute('class', 'btn btn-success');
?>

<div class="table">
    <?php echo $this->gview->form()->openTag($form); ?>
    <?php echo $this->gview->formElement($form->get("page")) ?>
    <table class="table table-bordered table-striped tauto">
        <tr>
            <td  colspan="<?php echo count($this->grid->getColumnCollection()) ?>">
                <div><?php echo $this->gview->formElement($submit) ?></div>
            </td>
        </tr>
        <tr>
            <?php foreach ($this->grid->getColumnCollection() as $column): ?>
                <?php if (!$column->getHidden()): ?>
                    <th style="text-align: center; font-size: 14px;">
                        <?php $name = $column->getName(); ?>
                <table>
                    <tr>
                    <td class="col-md-11"> <a  data-toggle="tooltip" title="<?php echo $column->getTooltip(); ?>" style="cursor: help">

                            <?php echo $column; ?>
                        </a></td>
                    <td class="col-md-1  padding2">
                        <div >  <a href="<?php echo $this->gview->url($this->route, array(), array('query' => array('orderBy' => $name, "orderDirection" => "ASC") + $this->routeParams), true); ?>" ><i class="fa fa-caret-up"></i></a> </div>

                        <div > <a href="<?php echo $this->gview->url($this->route, array(), array('query' => array('orderBy' => $name, "orderDirection" => "DESC") + $this->routeParams), true); ?>" ><i class="fa fa-caret-down"></i></a></div>
                    </td>
                    </tr>
                </table>




                </th>
            <?php endif; ?>
        <?php endforeach; ?>

        </tr>

        <tr>

            <?php foreach ($this->grid->getColumnCollection() as $column): ?>
                <?php if (!$column->getHidden()): ?>
                    <td class="text-center"> <?php
                        if ($column->getFilterActive()) {
                            echo $this->gview->formElement($form->get("f_" . $column->getName()));
                        }
                        ?></td>
                <?php endif; ?>
            <?php endforeach; ?>


        </tr>

        <?php if (count($this->grid->getRow())): ?>
            <?php foreach ($this->grid->getRow() as $data): ?>
                <tr>
                    <?php foreach ($this->grid->getColumnCollection() as $column): ?>
                        <?php if (!$column->getHidden()): ?>
                            <td >
                                <?php echo $column->getHtmlBegin(); ?>

                                <?php if ($column->getType() == "text"): ?>
                                    <?php echo nl2br($data[$column->getName()]); ?>
                                <?php endif; ?>

                                <?php if ($column->getType() == "boolean"): ?>
                                    <?php echo nl2br($this->gview->ColumnBoolean($column, $data[$column->getName()])); ?>
                                <?php endif; ?>

                                <?php if ($column->getType() == "datetime"): ?>
                                    <?php if (is_a($data[$column->getName()], "\datetime")): ?>
                                        <?php echo $data[$column->getName()]->format($column->getFormatDatetime()); ?>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php echo $column->getHtmlEnd(); ?>

                            </td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <?php echo $this->gview->form()->closeTag($form); ?>
</div>


<?php
echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', 'pagination', array("gview" => $this->gview,
    "routeParams" => $this->routeParams,
    'route' => $this->route));
?>
    

