<table class="table table-bordered table-striped">

    <?php foreach ($this->entity->toArray() as $key => $value): ?>

        <?php if (!is_array($value) && $value !== null): ?>
            <tr>
                <th style="width: 200px;"><?php echo ucfirst($key); ?></th>
                <td><?php echo $value; ?></td>

            </tr>
        <?php else: ?>
            <?php 
             $method = "get" . ucfirst($key);
            $o = $this->entity->{$method}(); ?>
            <?php if (!is_a($o, "Doctrine\ORM\PersistentCollection")): ?>
                <tr>
                    <th style="width: 200px;"><?php echo ucfirst($this->translate($key)); ?></th>
                    <td><?php
                        if (is_a($o, "DateTime")) {
                            echo $o->format("Y-m-d H:i:s");
                        } else {
                            echo $o;
                        }
                        ?></td>
                </tr>
            <?php endif; ?>

        <?php endif; ?>



    <?php endforeach; ?>

</table>
