<?php $record = $this->grid->getRecordDetail(); ?>
<div >
    <a class="btn btn-default" onclick="cdiListRecords()" >
        <?php echo $this->translate('List'); ?>
    </a>
    <?php if ($this->grid->getOptionEdit()): ?>
        <i class='btn btn-danger' onclick='cdiEditRecord(<?php echo $record->getId(); ?>)'>
            <?php echo $this->translate('Edit'); ?>
        </i>
    <?php endif; ?>
</div>

<div >

    <table class="table table-striped table-bordered">
        <?php foreach ((array) $record as $key => $value): ?>
            <tr>
                <th><?php echo $this->translate($key); ?></th>

                <td>
                    <?php if (substr($key, 0, 1) != '_'): ?>
                        <?php if (is_object($value)): ?>
                            <?php if (is_a($value, "DateTime")): ?>
                                <?php echo $value->format("Y-m-d H:i:s"); ?>
                            <?php else: ?> 
                                <?php echo $value; ?>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php echo $value; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<?php echo $this->CdiGridCrudAjax($this->grid->getId(),$this->url($this->route,array(),array(),true)); ?>
