<div class="row">

    <?php
    $form = clone $this->form;
//    var_dump($this->routeParams);
//    $url = $this->url($this->route, array(), array('query' => $this->routeParams), true);
//    $form->setAttribute('action', $url);
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>


    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">

            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#collapsePanel" aria-expanded="false" aria-controls="collapsePanel"><a style="cursor:pointer"><i class="fa fa-download"> Descargar CSV</i></a> </div>



                <div class="panel-body collapse" id="collapsePanel">
                      <?php
                    $element = $form->get('csvExport');
                    ?>
                       <?php echo $this->formElement($element); ?>

                    <?php
                    $element = $form->get('nameCsv');
                    ?>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 ">
                        <div class="input-group date <?php if ($this->formElementErrors($element)) echo " has-error" ?> nopadding nomargin colorBlack">   
                            <label class="col-lg-6 col-md-6 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-lg-6 col-md-6">
                                <?php echo $this->formElement($element); ?>
                            </div>
                        </div>
                        <?php if ($this->formElementErrors($element)) : ?>
                            <div class="has-error">
                                <?php
                                // Imprimo los errores
                                echo $this->formElementErrors()
                                        ->setMessageOpenFormat('<span class="help-block">')
                                        ->setMessageSeparatorString('</span><span class="help-block">')
                                        ->setMessageCloseString('</span>')
                                        ->render($element);
                                ?>
                            </div>
                        <?php endif; ?>



                    </div>



                    <?php
                    $element = $form->get('separatorCsv');
                    ?>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 ">

                        <div  class="input-group date <?php if ($this->formElementErrors($element)) echo " has-error" ?> nopadding nomargin colorBlack">   
                            <label class="col-lg-5 col-md-5 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-lg-7 col-md-7">
                                <?php echo $this->formElement($element); ?>
                            </div> 
                        </div>     
                        <?php if ($this->formElementErrors($element)) : ?>
                            <div class="has-error">
                                <?php
                                // Imprimo los errores
                                echo $this->formElementErrors()
                                        ->setMessageOpenFormat('<span class="help-block">')
                                        ->setMessageSeparatorString('</span><span class="help-block">')
                                        ->setMessageCloseString('</span>')
                                        ->render($element);
                                ?>
                            </div>
                        <?php endif; ?>



                    </div>



                    <?php $element = $form->get('submit'); ?>
                    <?php $element->setAttribute('class', " btn btn-info  col-lg-12 col-md-12 col-sm-12 col-xs-12"); ?>
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 ">
                        <div  class="form-group nopadding nomargin colorBlack">   
                            <?php echo $this->formElement($element); ?>
                        </div>
                    </div>

                    <?php echo $this->form()->closeTag($form); ?>

                    <!--FIN FORMULARIO-->

                </div>


            </div>
      
    </div>

   

</div>
<script type="text/javascript">
    $(function() {
        $('#datetimepicker1').datetimepicker({
            pickTime: false,
            language: 'es'
        });

        $('#datetimepicker2').datetimepicker(
                {
                    pickTime: false,
                    language: 'es'
                });
    });
</script>