<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="col-lg-12">    
        <div class="input-group">
            <span class="input-group-addon">
                <?php echo $this->formElement($this->element); ?>
            </span>
            <input type="text" class="form-control" aria-label="..." placeholder="<?php echo $this->element->getName(); ?>" disabled="disabled">
        </div>


    </div>
</div>
