<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="col-lg-12">    

        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                    <span class="caret"></span> <span class="sr-only">Toggle Dropdown</span> 
                </button>
                <ul class="dropdown-menu"> 
                    <li><a onclick="changeOp('<?php echo $this->element->getName(); ?>','')"><?php echo $this->translate("like (Default)"); ?></a></li> 
                    <li><a onclick="changeOp('<?php echo $this->element->getName(); ?>','==')"><?php echo $this->translate("equal"); ?> ==</a></li> 
                    <li><a onclick="changeOp('<?php echo $this->element->getName(); ?>','>')"><?php echo $this->translate("greater"); ?> ></a></li>
                    <li><a onclick="changeOp('<?php echo $this->element->getName(); ?>','<')"><?php echo $this->translate("less"); ?> <</a></li> 
                      <li><a onclick="changeOp('<?php echo $this->element->getName(); ?>','val1 >< val2')"><?php echo $this->translate("between"); ?> ><</a></li> 

                </ul>
            </div>
            <?php echo $this->formElement($this->element); ?>
        </div>

        <?php if ($element->getOption('description')): ?>
            <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
        <?php endif; ?>
        <?php if ($this->formElementErrors($this->element)) : ?>
            <?php
            // Imprimo los errores
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($element);
            ?>

        <?php endif; ?>
    </div>
</div>

