<br>
<div class="row container-fluid">

    <div class="panel panel-default">
        <div class="panel-heading">Edit Record</div>
        <div class="panel-body">
            <?php
            $form = $this->grid->getCrudForm();
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute("action", "javascript:cdiForm('".$form->getName()."')");
            $form->prepare();
//$form->setAttribute('action', $this->url('application', array('action' => 'edit')))->prepare();
            echo $this->form()->openTag($form);
            ?>


            <?php $multiplo = 2; ?>
            <?php $countRow = 2; ?>
            <?php foreach ($form as $element) : ?>

                <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
                        <?php echo $this->formElement($element); ?>
                        <?php break; ?>
                    <?php case "submit": ?>
                        <?php $element->setAttribute('class', 'btn btn-success'); ?>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-xs-12 ">
                                <div  class="form-group">
                                    <div class="col-lg-3 col-md-3 col-xs-12">
                                        <?php echo $this->formElement($element); ?>
                                        <a class="btn btn-default" onclick="cdiListRecords()" >Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php break; ?>
                    <?php default: ?>

                        <?php
                        $element->setAttribute('class', 'form-control');
                        //  ->setAttribute('placeholder', $element->getLabel());
                        ?>
                        <div class="row" id="row_<?php echo $element->getName() ?>">


                            <div class="col-lg-12 col-md-12 col-xs-12">
                                <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">

                                    <label class="col-lg-4 col-md-4 control-label"><?php echo ucfirst($this->translate($element->getLabel())) ?></label>

                                    <div class="col-lg-8 col-md-8">
                                        <?php echo $this->formElement($element); ?>
                                        <?php if ($element->getOption('description')): ?>
                                            <p class="help-block"><?php echo $element->getOption('description') ?></p>
                                        <?php endif; ?>
                                        <?php if ($this->formElementErrors($element)) : ?>
                                            <?php
                                            // Imprimo los errores
                                            echo $this->formElementErrors()
                                                    ->setMessageOpenFormat('<span class="help-block">')
                                                    ->setMessageSeparatorString('</span><span class="help-block">')
                                                    ->setMessageCloseString('</span>')
                                                    ->render($element);
                                            ?>

                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>

                        </div>


                        <?php break; ?>
                <?php endswitch; ?>

            <?php endforeach; ?>

            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>

<?php echo $this->CdiGridCrudAjax($this->grid->getId(),$this->url($this->route,array(),array(),true)); ?>
