
<?php
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
?>


<?php $multiplo = 2; ?>
<?php $countRow = 2; ?>
<?php foreach ($form as $element) : ?>

    <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
            <?php echo $this->formElement($element); ?>
            <?php break; ?>
        <?php
        case "submit" :
        case "button" :
            ?>
     
                <div class="col-lg-12 col-md-12 col-xs-12 ">
                    <div  class="form-group">
                        <div class="col-lg-12 col-md-12 col-xs-12 ">
                               <?php echo $this->formElement($element); ?>       
                        </div>
                    </div>
                </div>
          
            <?php
            break;
        case "select" :
            ?>

            <?php
            $element->setAttribute('class', 'form-control');
             $element->setAttribute('placeholder', $element->getName());
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 45px">
                <?php echo $this->partial('cdidatagrid/form/filter-element-select', array('element' => $element)); ?>
            </div>

            <?php
            break;
        case "checkbox" :
            ?>

            <?php
           // $element->setAttribute('class', 'form-control');
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 45px">
                <?php echo $this->partial('cdidatagrid/form/filter-element-checkbox', array('element' => $element)); ?>
            </div>

            <?php
            break;
        default:
            ?>

            <?php
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getName());
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 45px">
                <?php echo $this->partial('cdidatagrid/form/filter-element', array('element' => $element)); ?>
            </div>

            <?php break; ?>
    <?php endswitch; ?>
  
<?php endforeach; ?>

<?php echo $this->form()->closeTag($form); ?>

<script type="text/javascript">
    function changeOp(element, value) {
        $('[name="' + element + '"]').val(value);
    }
</script>
