
<div class="padding5">
    <?php if ($this->grid->getOptionAdd()): ?>
        <?php $addBtn = $this->grid->getAddBtn(); ?>
        <?php echo $this->CdiGridBtnAdd($addBtn["name"], $addBtn["class"], $addBtn["value"], "cdiAddRecord()"); ?>

    <?php endif; ?> 


</div>

<div >
    <?php
    $form = $this->grid->getFormFilters();
    $form->prepare();
    $submit = $form->get("submit");
    $submit->setAttribute('class', 'btn btn-success');
    ?>
    <?php //echo $this->formElement($submit)       ?>

    <?php echo $this->form()->openTag($form); ?>

    <div class="row container-fluid">
        <div class="panel panel-default nomargin">
            <div class="panel-heading padding2 text-center">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseFilter" aria-expanded="true" aria-controls="collapseFilter" >
                    Filtros
                </a>
            </div>
            <div id="collapseFilter" class="panel-body panel-collapse collapse"  role="tabpanel" aria-labelledby="headingOne">
                <div id="adest">
                    <?php echo $this->partial("cdidatagrid/form/form-filter", array("form" => $form)); ?>
                </div>

            </div>

        </div>
    </div>

    <?php echo $this->form()->closeTag($form); ?>
</div>

<div class="table">


    <?php echo $this->formElement($form->get("page")) ?>
    <table class="table table-bordered <?php echo $this->grid->getTableClass(); ?>">

        <tr>
            <?php foreach ($this->grid->getColumns() as $column): ?>
                <?php if (!$column->getHidden()): ?>
                    <th style="text-align: center; font-size: 14px;">
                        <?php $name = $column->getName(); ?>
                        <?php echo $this->translate((string) $column); ?>
                        <?php if ($column->getType() != "extra"): ?>
                            <?php if ($this->grid->getOrderBy() == $column->getName()): ?>
                                <?php if ($this->grid->getOrderDirection() == "DESC"): ?>
                                    <a class="fa fa-sort-asc" href="<?php echo $this->url($this->route, array(), array('query' => array('orderBy' => $name, "orderDirection" => "ASC") + $this->routeParams), true); ?>"></a>
                                <?php elseif ($this->grid->getOrderDirection() == "ASC"): ?>
                                    <a class="fa fa-sort-desc" href="<?php echo $this->url($this->route, array(), array('query' => array('orderBy' => $name, "orderDirection" => "DESC") + $this->routeParams), true); ?>"></a>
                                <?php endif; ?>
                            <?php else: ?>
                                <a class="fa fa-sort" href="<?php echo $this->url($this->route, array(), array('query' => array('orderBy' => $name, "orderDirection" => "DESC") + $this->routeParams), true); ?>"></a>
                            <?php endif; ?>

                        <?php endif; ?>

                    </th>
                <?php endif; ?>
            <?php endforeach; ?>

        </tr>

        <?php if (count($this->grid->getRow())): ?>
            <?php foreach ($this->grid->getRow() as $data): ?>
                <tr>
                    <?php foreach ($this->grid->getColumns() as $column): ?>
                        <?php if (!$column->getHidden()): ?>
                            <td class="<?php echo $column->getTdClass(); ?>">
                                <?php //TODO - echo $column->getHtmlBegin(); ?>
                            
                                <?php echo $this->CdiGridField($column, $data); ?>

                                <?php //TODO - echo $column->getHtmlEnd(); ?>

                            </td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>

</div>

<?php
echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
    'route' => $this->route));
?>


<?php echo $this->CdiGridCrud(); ?>

